import { promises as fs } from "node:fs";
import path from "node:path";
import type { Run } from "@/lib/types";
import BoardHeader from "@/components/board/BoardHeader";
import WedgeBanner from "@/components/board/WedgeBanner";
import TaskList from "@/components/board/TaskList";
import TimelineGantt from "@/components/board/TimelineGantt";
import ExecutiveSummary from "@/components/board/ExecutiveSummary";
import SourceFooter from "@/components/board/SourceFooter";

// /board/[id] — the shareable launch board. This page IS the deliverable.
// No nav, no footer chrome, no live trace. A single print-friendly document
// that the user hands to their team or drops into an investor update.
//
// Next 16: dynamic-route params are a Promise. `await params` on the
// server. Same loader pattern as /results/[id].
type PageParams = Promise<{ id: string }>;

export const dynamic = "force-dynamic";

async function loadDemoRunServer(): Promise<Run> {
  const file = path.join(process.cwd(), "public", "cache", "demo-linear.json");
  const raw = await fs.readFile(file, "utf-8");
  return JSON.parse(raw) as Run;
}

export async function generateMetadata({ params }: { params: PageParams }) {
  const { id } = await params;
  return {
    title: `Launch board · ${id} · Shadow Launch`,
    description:
      "Shareable 14-day launch board generated by Shadow Launch. Tasks, timeline, and executive summary from the synthetic jury verdict.",
  };
}

export default async function BoardPage({ params }: { params: PageParams }) {
  const { id: runId } = await params;

  // Lane A: unknown ids still render via the cached demo JSON. Same
  // fallback pattern as /results/[id] and /run/[id].
  let run: Run | null = null;
  let loadError: string | null = null;
  try {
    run = await loadDemoRunServer();
  } catch (err) {
    loadError = err instanceof Error ? err.message : String(err);
  }

  if (loadError || !run) {
    return (
      <main className="mx-auto max-w-3xl px-6 py-24 font-serif">
        <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-[var(--accent)]">
          Board failed to load
        </p>
        <h1 className="mt-3 text-3xl text-[var(--ink)]">
          {loadError ?? "unknown error"}
        </h1>
        <p className="mt-4 text-[var(--ink-soft)]">
          Expected <code className="font-mono">cache/demo-linear.json</code> in{" "}
          <code className="font-mono">web/public/cache/</code>.
        </p>
      </main>
    );
  }

  // Use the id the URL asked for as the surfaced run_id so unknown ids
  // still feel native. The underlying data is the cached demo run.
  const runForDisplay: Run = { ...run, run_id: runId ?? run.run_id };

  const tasks = runForDisplay.launch_board?.tasks ?? [];
  const timeline = runForDisplay.launch_board?.timeline ?? [];
  const summary = runForDisplay.launch_board?.executive_summary ?? "";

  return (
    <>
      {/* Print rules scoped to this page. Strips body grain/vignette pseudo-elements
          from globals.css and forces cream-on-ink-dark for clean PDF output. */}
      <style>{`
        @media print {
          @page { margin: 14mm; size: A4; }
          html, body { background: #ece4d2 !important; color: #0c0c0a !important; }
          body::before, body::after { display: none !important; }
          .board-print-hide { display: none !important; }
          section, header, footer { break-inside: avoid-page; }
          * { box-shadow: none !important; }
        }
      `}</style>

      <main
        className="relative z-[1] bg-[var(--paper)] text-[var(--ink)]"
        data-shadow-launch-board
      >
        <BoardHeader run={runForDisplay} />
        <WedgeBanner run={runForDisplay} />
        <TaskList tasks={tasks} />
        <TimelineGantt tasks={tasks} timeline={timeline} />
        <ExecutiveSummary summary={summary} />
        <SourceFooter run={runForDisplay} />
      </main>
    </>
  );
}
