"""initial v2 schema

Revision ID: 89a12a69720a
Revises: 
Create Date: 2026-04-18 13:21:55.374240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89a12a69720a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minds_sparks',
    sa.Column('persona_id', sa.String(length=32), nullable=False),
    sa.Column('spark_id', sa.String(length=64), nullable=False),
    sa.Column('panel_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('system_prompt_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('persona_id')
    )
    op.create_table('runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('brand_voice_guide', sa.Text(), nullable=True),
    sa.Column('target_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_constraint', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_usd_total', sa.Float(), nullable=False),
    sa.Column('kalibr_trace_capsule_id', sa.String(length=128), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('angles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_index(op.f('ix_campaigns_run_id'), 'campaigns', ['run_id'], unique=False)
    op.create_table('competitors',
    sa.Column('competitor_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('positioning', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('discovery_source', sa.String(length=32), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('competitor_id')
    )
    op.create_index(op.f('ix_competitors_run_id'), 'competitors', ['run_id'], unique=False)
    op.create_table('content_calendars',
    sa.Column('calendar_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('days_span', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('calendar_id')
    )
    op.create_index(op.f('ix_content_calendars_run_id'), 'content_calendars', ['run_id'], unique=False)
    op.create_table('discourse_items',
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_discourse_items_run_id'), 'discourse_items', ['run_id'], unique=False)
    op.create_table('image_assets',
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('campaign_angle_id', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.LargeBinary(), nullable=False),
    sa.Column('kalibr_trace_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_image_assets_run_id'), 'image_assets', ['run_id'], unique=False)
    op.create_table('kalibr_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('goal', sa.String(length=64), nullable=False),
    sa.Column('from_model', sa.String(length=64), nullable=True),
    sa.Column('to_model', sa.String(length=64), nullable=True),
    sa.Column('failure_category', sa.String(length=64), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=True),
    sa.Column('cost_usd_delta', sa.Float(), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_kalibr_events_run_id'), 'kalibr_events', ['run_id'], unique=False)
    op.create_table('persona_reactions',
    sa.Column('reaction_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('persona_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('top_objection', sa.Text(), nullable=True),
    sa.Column('rebuts_persona_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reaction_id')
    )
    op.create_index(op.f('ix_persona_reactions_run_id'), 'persona_reactions', ['run_id'], unique=False)
    op.create_table('product_profiles',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=False),
    sa.Column('one_liner', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('positioning_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('implicit_audience', sa.Text(), nullable=False),
    sa.Column('tone_inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('messaging_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kalibr_trace_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('trace_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('kalibr_model', sa.String(length=64), nullable=True),
    sa.Column('kalibr_cost_delta_usd', sa.Float(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_trace_events_run_id'), 'trace_events', ['run_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('verdict_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('consensus_score', sa.Float(), nullable=False),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('dissenting_personas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('verdict_id')
    )
    op.create_index(op.f('ix_verdicts_run_id'), 'verdicts', ['run_id'], unique=False)
    op.create_table('calendar_slots',
    sa.Column('slot_id', sa.String(length=64), nullable=False),
    sa.Column('calendar_id', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('post_type', sa.String(length=16), nullable=False),
    sa.Column('copy', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('posting_time', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['content_calendars.calendar_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_index(op.f('ix_calendar_slots_calendar_id'), 'calendar_slots', ['calendar_id'], unique=False)
    op.create_table('social_snapshots',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('competitor_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('handle', sa.Text(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=True),
    sa.Column('posting_cadence_per_week', sa.Float(), nullable=True),
    sa.Column('top_posts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.competitor_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('competitor_id', 'platform', name='uq_snapshot_competitor_platform')
    )
    op.create_index(op.f('ix_social_snapshots_competitor_id'), 'social_snapshots', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_social_snapshots_run_id'), 'social_snapshots', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_snapshots_run_id'), table_name='social_snapshots')
    op.drop_index(op.f('ix_social_snapshots_competitor_id'), table_name='social_snapshots')
    op.drop_table('social_snapshots')
    op.drop_index(op.f('ix_calendar_slots_calendar_id'), table_name='calendar_slots')
    op.drop_table('calendar_slots')
    op.drop_index(op.f('ix_verdicts_run_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_trace_events_run_id'), table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_table('product_profiles')
    op.drop_index(op.f('ix_persona_reactions_run_id'), table_name='persona_reactions')
    op.drop_table('persona_reactions')
    op.drop_index(op.f('ix_kalibr_events_run_id'), table_name='kalibr_events')
    op.drop_table('kalibr_events')
    op.drop_index(op.f('ix_image_assets_run_id'), table_name='image_assets')
    op.drop_table('image_assets')
    op.drop_index(op.f('ix_discourse_items_run_id'), table_name='discourse_items')
    op.drop_table('discourse_items')
    op.drop_index(op.f('ix_content_calendars_run_id'), table_name='content_calendars')
    op.drop_table('content_calendars')
    op.drop_index(op.f('ix_competitors_run_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_campaigns_run_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('runs')
    op.drop_table('minds_sparks')
    # ### end Alembic commands ###
